/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './*.html',
    './*.js',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#f2ca50',
        'primary-container': '#d4af37',
        'primary-fixed': '#ffe088',
        'primary-fixed-dim': '#e9c349',
        secondary: '#d1c6a1',
        'secondary-fixed': '#eee2bc',
        'secondary-fixed-dim': '#d1c6a1',
        surface: '#10131a',
        'surface-container': '#1d1f27',
        'surface-container-low': '#191b23',
        'surface-container-lowest': '#0b0e15',
        'surface-container-high': '#272a32',
        'surface-container-highest': '#32353d',
        'on-primary': '#3c2f00',
        'on-primary-container': '#554300',
        'on-surface': '#e1e2ec',
        'on-surface-variant': '#d0c5af',
        outline: '#99907c',
        'outline-variant': '#4d4635',
      },
      spacing: {
        gutter: '1.5rem',
        'gutter-desktop': '2.5rem',
        margin: '1.5rem',
        'margin-tablet': '3rem',
        'margin-desktop': '5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.75rem',
        'space-xl': '3rem',
        'space-2xl': '5rem',
      },
      fontFamily: {
        body: ['Plus Jakarta Sans'],
        display: ['Bodoni Moda'],
      },
      fontSize: {
        'body-md': ['0.9375rem', { lineHeight: '1.625rem', letterSpacing: '0.01em', fontWeight: '300' }],
        'body-lg': ['1.125rem', { lineHeight: '1.875rem', letterSpacing: '0.01em', fontWeight: '300' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.375rem', letterSpacing: '0.02em', fontWeight: '400' }],
        title: ['1.125rem', { lineHeight: '1.75rem', letterSpacing: '0.04em', fontWeight: '500' }],
        'label-lg': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.14em', fontWeight: '600' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.18em', fontWeight: '600' }],
        'label-sm': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.22em', fontWeight: '600' }],
        'headline-sm': ['1.5rem', { lineHeight: '2rem', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['2rem', { lineHeight: '2.5rem', letterSpacing: '0', fontWeight: '500' }],
        'headline-lg': ['3rem', { lineHeight: '3.5rem', letterSpacing: '-0.01em', fontWeight: '400' }],
        display: ['4.5rem', { lineHeight: '5rem', letterSpacing: '-0.02em', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};